### ISSUE TITLE
Feature request : Two way data binding

### ISSUE THREAD

**Issue by zamronypj** [mr-highball/nyx#1]
Allow two way data binding. For example

`TEdit` will be translated to `<input type="text">`

When its Text properties is set 
```
var edt1 : TEdit;
...
edt1.text := 'hello';
```
Its DOM element value is updated accordingly. When user type something then `edt1.text` is updated too.

**Comment by mr-highball** [comment]
This is a planned feature for all properties. The only property actually implemented at the time of writing this is a button -> text. As you can see from the below source lines, the text for a browser button pulls straight from the dom element, and writes straight to it (no middle man property)
https://github.com/mr-highball/nyx/blob/master/src/nyx.element.button.browser.pas#L90
https://github.com/mr-highball/nyx/blob/master/src/nyx.element.button.browser.pas#L95

If this addresses the concern, please close the issue otherwise I'll be glad to elaborate further

**Comment by zamronypj** [comment]
If that is planned feature then I will close this issue. Thank you
