### ISSUE TITLE
Feature request : ability to use CSS

### ISSUE THREAD

**Issue by zamronypj** [mr-highball/nyx#2]
Add ability to change look and feel of a visual control with cascading style sheet (CSS).

CSS can be change at runtime and its change is reflected with actual DOM CSS.

**Comment by mr-highball** [comment]
@zamronypj this is already possible (for browser based elements)
The tester uses [mvp] to style the entire app (https://github.com/andybrewer/mvp/tree/c80d4514137a9c0595f43cec9a87268faf8c9aa7)

https://github.com/mr-highball/nyx/blob/master/test/nyx_browser_test.html#L4

Additionally, you won't be limited to access the "jselement" of a browser element to get direct access to control specific styling if desired,
https://github.com/mr-highball/nyx/blob/master/src/nyx.element.browser.pas#L48

If this answers the question, please close the issue, otherwise I'll be glad to look further
